obj-y += board.o
obj-y += flash-header-dmo-imx6-ppc.dcd.o \
         flash-header-dmo-imx6dl-ppc_2G_32bit.dcd.o \
         flash-header-dmo-imx6dl-ppc_4G_32bit.dcd.o \
         flash-header-dmo-imx6q-ppc_2G_64bit.dcd.o \
         flash-header-dmo-imx6q-ppc_4G_32bit.dcd.o \
         flash-header-dmo-imx6q-ppc_4G_64bit.dcd.o
         
extra-y += flash-header-dmo-imx6-ppc.dcd.S \
           flash-header-dmo-imx6dl-ppc_2G_32bit.dcd.S \
           flash-header-dmo-imx6dl-ppc_4G_32bit.dcd.S \
           flash-header-dmo-imx6q-ppc_2G_64bit.dcd.S \
           flash-header-dmo-imx6q-ppc_4G_32bit.dcd.S \
           flash-header-dmo-imx6q-ppc_4G_64bit.dcd.S

extra-y += flash-header-dmo-imx6-ppc.dcd \
           flash-header-dmo-imx6dl-ppc_2G_32bit.dcd \
           flash-header-dmo-imx6dl-ppc_4G_32bit.dcd \
           flash-header-dmo-imx6q-ppc_2G_64bit.dcd \
           flash-header-dmo-imx6q-ppc_4G_32bit.dcd \
           flash-header-dmo-imx6q-ppc_4G_64bit.dcd

lwl-y += lowlevel.o
