obj-y += board.o
obj-y += flash-header-dmo-imx6dl-ppc.dcd.o \
	 flash-header-dmo-imx6q-ppc.dcd.o
extra-y += flash-header-dmo-imx6dl-ppc.dcd.S \
	   flash-header-dmo-imx6q-ppc.dcd.S
extra-y += flash-header-dmo-imx6dl-ppc.dcd \
	   flash-header-dmo-imx6q-ppc.dcd
lwl-y += lowlevel.o
