#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "Automountpoints"
	exit
fi

# automount tftp server based on $eth0.serverip

mkdir -p /mnt/tftp
automount /mnt/tftp 'ifup eth0 && mount -t tftp $eth0.serverip /mnt/tftp'

if [ "$nv.global.nfs.kernels" ]; then
	mkdir -p /mnt/nfs
	automount /mnt/nfs 'ifup eth0 && mount -t nfs $eth0.serverip:$nv.global.nfs.kernels /mnt/nfs'
fi

mkdir -p /mnt/mmc2
mkdir -p /mnt/mmc3

automount -d /mnt/mmc2 'mmc2.probe=1 && [ -e /dev/mmc2.0 ] && mount /dev/mmc2.0 /mnt/mmc2'
automount -d /mnt/mmc3 'mmc3.probe=1 && [ -e /dev/mmc3.0 ] && mount /dev/mmc3.0 /mnt/mmc3'
