obj-y += board.o
obj-y += flash-header-edmqmx6-q-d.dcd.o \
	 flash-header-edmqmx6-dl.dcd.o
extra-y += flash-header-edmqmx6-q-d.dcd.S \
	   flash-header-edmqmx6-dl.dcd.S
extra-y += flash-header-edmqmx6-q-d.dcd \
	   flash-header-edmqmx6-dl.dcd
lwl-y += lowlevel.o
