#!/bin/sh

if [ "$1" = menu ]; then
	exit
fi

global.bootm.image="/mnt/ata0/zImage"
global.bootm.initrd="/mnt/ata0/initramfs"

if [ "$nv.display.type" = "LVDS" ]; then
	localvideo="HDMI-A-1:d"
else
	localvideo="LVDS-1:d"
fi

if [ "$global.display.size" = "" ]; then
	global.bootm.oftree="/mnt/ata0/oftree"
else
	dts_detect /mnt/ata0/ $global.display.size

	if [ "$global.detected.dts" != "" ]; then
		global.bootm.oftree="/mnt/ata0/"$global.detected.dts
		localvideo="HDMI-A-1:d"
	else
		global.bootm.oftree="/mnt/ata0/oftree"
	fi
fi

global.linux.bootargs.dyn.root="root=/dev/sda2 rootwait video=-32 video=$localvideo fsck.repair=yes"
