#!/bin/sh

if [ "$1" = menu ]; then
	exit
fi

global.bootm.image="/mnt/ata0/zImage"
global.bootm.oftree="/mnt/ata0/oftree"
global.bootm.initrd="/mnt/ata0/initramfs"

if [ "$nv.display.type" = "LVDS" ]; then
	localvideo="HDMI-A-1:d"
else
	localvideo="LVDS-1:d"
fi

global.linux.bootargs.dyn.root="root=/dev/sda2 rootwait video=-32 video=$localvideo fsck.repair=yes"
