#!/bin/sh

if [ "$1" = menu ]; then
	exit
fi

global.bootm.image="/mnt/ata0/zImage"
global.bootm.initrd="/mnt/ata0/initramfs"

if [ "$global.display.size" = "" ]; then
	if [ -e "/mnt/mmc3/oftree" ]; then
		global.bootm.oftree="/mnt/ata0/oftree"
	else
		dts_detect /mnt/mmc3/ "HDMI"
		if [ "$global.detected.dts" != "" ]; then
			global.bootm.oftree="/mnt/mmc3/"$global.detected.dts
		else
			global.bootm.oftree="/mnt/mmc3/oftree"
		fi
	fi
else
	dts_detect /mnt/ata0/ $global.display.size

	if [ "$global.detected.dts" != "" ]; then
		global.bootm.oftree="/mnt/ata0/"$global.detected.dts
	else
		global.bootm.oftree="/mnt/ata0/oftree"
	fi
fi

global.linux.bootargs.dyn.root="root=/dev/sda2 rootwait video=-32 fsck.repair=yes"
