#!/bin/sh

global.bootm.image="/mnt/mmc3/zImage"
global.bootm.oftree="/mnt/mmc3/oftree"
global.bootm.initrd="/mnt/mmc3/initramfs"

if [ "$nv.display.type" = "LVDS" ]; then
	localvideo="HDMI-A-1:d"
else
	localvideo="LVDS-1:d"
fi

global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootwait video=-32 video=$localvideo fsck.repair=yes"
