#!/bin/sh

global.bootm.image="/mnt/mmc3/zImage"
global.bootm.initrd="/mnt/mmc3/initramfs"

if [ "$nv.display.type" = "LVDS" ]; then
	localvideo="HDMI-A-1:d"
else
	localvideo="LVDS-1:d"
fi


if [ "$global.display.size" = "" ]; then
	global.bootm.oftree="/mnt/mmc3/oftree"
else
	dts_detect /mnt/mmc3/ $global.display.size

	if [ "$global.detected.dts" != "" ]; then
		global.bootm.oftree="/mnt/mmc3/"$global.detected.dts
		localvideo="HDMI-A-1:d"
	else
		global.bootm.oftree="/mnt/mmc3/oftree"
	fi
fi

global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootwait video=-32 video=$localvideo fsck.repair=yes"
