#!/bin/sh

path="/mnt/nfs"

global.bootm.image="${path}/${global.user}-linux-${global.hostname}"

oftree="${path}/${global.user}-oftree-${global.hostname}"
if [ -f "${oftree}" ]; then
	global.bootm.oftree="$oftree"
fi

nfsroot="/home/${global.user}/nfsroot/${global.hostname}"
bootargs-ip

if [ "$nv.display.type" = "LVDS" ]; then
	localvideo="HDMI-A-1:d"
else
	localvideo="LVDS-1:d"
fi

initramfs="${path}/${global.user}-initramfs-${global.hostname}"
if [ -f "${initramfs}" ]; then
	global.bootm.initrd="initramfs"
else
	global.linux.bootargs.dyn.root="root=/dev/nfs nfsroot=$nfsroot,v3,tcp video=-32 video=$localvideo"
fi
