#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "MMC"
	exit
fi

global.bootm.image="/mnt/emmc/zImage"
global.bootm.oftree="/mnt/emmc/oftree"
global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootfstype=ext3 rootwait"
